Feature/microservice status
fga-eps-mds/2018.2-FGAPP-produto pull request #20
Opened 2018-10-14 17:48 UTC by gustavolima00

## Descrição
Mudança na URL raiz do micro serviço, agora passa se tornar uma API com método GET apenas, mostrando o status do micro serviço, seu nome e versão através de um json:
![image](https://user-images.githubusercontent.com/32046134/46920140-3387ac00-cfc0-11e8-9f71-2c983fe332bc.png)

**Solução parcial da issue**
fga-eps-mds/2018.2-iFood#190

Tarefas gerais realizadas
* Pegar dado de versão que esta no arquivo VERSION na raiz do repositório

2018-10-14 18:27 UTC, lucasca73 requested changes
Poderia levar a função de ler o arquivo para uma helper?

2018-10-14 18:46 UTC, gustavolima00 commented
Atualizei o arquivo, mudando seu nome para version_helper, por se tratar de uma função específica. sua importação no arquivo url.py também muda ficando da seguinte forma 
```python
from .version_helper import status
```

2018-10-14 22:04 UTC, lucasca73 commented
Esse problema de não conseguir encontrar o serviço foi resolvido, agora só essa questão mesmo de corrigir a view, deixar somente a função de pegar do arquivo em uma helper.

2018-10-15 01:36 UTC, gustavolima00 commented
A view foi recolocada com a função em um arquivo helper.

2018-10-15 16:06 UTC, lucasca73 approved these changes

2018-10-15 16:06 UTC, merged