Feature/integration
fga-eps-mds/2018.2-FGAPP-produto pull request #9
Opened 2018-09-29 03:07 UTC by gustavolima00

Co-authored-by: Gustavo Marques <gustavomarques.gml@gmail.com>
Co-authored-by: Leonardo Medeiros <leonardomedeiros.6@gmail.com>

## Pull request 
(FIX) fga-eps-mds/2018.2-iFood#110

Foi adicionado '/' ao final de todas URLs
Foi criada requisição e verificação de token pelas funçoes 
Mudanças mais significativas em algumas URLs

## Branches usadas no desenvolvimento
2018.2-iFood (feature/integration)
2018.2-FGAPP-login (feature/integration)
2018.2-FGAPP-produto (feature/integration)
2018.2-FGAPP-vendas (feature/integration)
2018.2-FGAPP-FrontEnd (vendas-app/integration)

2018-10-02 22:20 UTC, andrelucax requested changes
Testes nao estao passando. Provavelmente porque foi adicionada barra ("/") nas URLs e nos testes nao. Verifique

2018-10-03 05:31 UTC, leomedeiros1 commented
Testes corrigidos e conflitos resolvidos. Obrigado @andrelucax , favor verificar novamente.

2018-10-03 22:12 UTC, andrelucax commented on product_microservice/products/tests.py
> +import json
Esse import parece nao estar sendo utilizado

2018-10-03 22:29 UTC, leomedeiros1 commented on product_microservice/products/tests.py
> +import json
Resolvido, @andrelucax .

2018-10-03 22:31 UTC, andrelucax approved these changes

2018-10-03 22:31 UTC, merged